### ISSUE TITLE
Exception during application startup

### ISSUE THREAD

**Issue by kppgs** [DevComPack/setupmaker#2]
```
c:\Users\user\DCP Setup Maker>java -jar dcpsetupmaker.jar
[DEBUG] Data loaded to memory
Exception: Failed to execute script:

                                                        importPackage(org.apache.pivot.wtk);
                                                        function buttonPressed(button) {
                                                            Alert.alert(MessageType.INFO, "DCP Setup Maker is developed by Said SAID EL IMAM, and powered by IzPack 4.3.5 and NuGet. www.devcompack.com/setupmaker ", master);
                                                        }

org.apache.pivot.serialization.SerializationException: Failed to execute script:

                                                        importPackage(org.apache.pivot.wtk);
                                                        function buttonPressed(button) {
                                                            Alert.alert(MessageType.INFO, "DCP Setup Maker is developed by Said SAID EL IMAM, and powered by IzPack 4.3.5 and NuGet. www.devcompack.com/setupmaker ", master);
                                                        }

        at org.apache.pivot.beans.BXMLSerializer.reportException(BXMLSerializer.java:1438)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1293)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:447)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:633)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:606)
        at com.dcp.sm.gui.pivot.Master.startup(Master.java:161)
        at org.apache.pivot.wtk.DesktopApplicationContext$2.run(DesktopApplicationContext.java:641)
        at org.apache.pivot.wtk.ApplicationContext$QueuedCallback.run(ApplicationContext.java:1656)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.script.ScriptException: ReferenceError: "importPackage" is not defined in <eval> at line number 2
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1291)
        ... 20 more
Caused by: <eval>:2 ReferenceError: "importPackage" is not defined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
        at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1426)
        at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:2)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        ... 25 more
Exception: Failed to execute script:

                        importClass(org.apache.pivot.wtk.Component);
                        importClass(org.apache.pivot.wtk.Keyboard);

                        function keyPressed(component, keyCode, keyLocation) {
                            if (keyCode == Keyboard.KeyCode.ENTER) {
                                btGroupAdd.press();
                            }
                        }

org.apache.pivot.serialization.SerializationException: Failed to execute script:

                        importClass(org.apache.pivot.wtk.Component);
                        importClass(org.apache.pivot.wtk.Keyboard);

                        function keyPressed(component, keyCode, keyLocation) {
                            if (keyCode == Keyboard.KeyCode.ENTER) {
                                btGroupAdd.press();
                            }
                        }

        at org.apache.pivot.beans.BXMLSerializer.reportException(BXMLSerializer.java:1438)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1293)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:447)
        at org.apache.pivot.beans.BXMLSerializer.processStartElement(BXMLSerializer.java:909)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:442)
        at org.apache.pivot.beans.BXMLSerializer.processStartElement(BXMLSerializer.java:909)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:442)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:633)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:606)
        at com.dcp.sm.gui.pivot.Master.startup(Master.java:161)
        at org.apache.pivot.wtk.DesktopApplicationContext$2.run(DesktopApplicationContext.java:641)
        at org.apache.pivot.wtk.ApplicationContext$QueuedCallback.run(ApplicationContext.java:1656)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 2
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1291)
        ... 24 more
Caused by: <eval>:2 ReferenceError: "importClass" is not defined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
        at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1426)
        at jdk.nashorn.internal.scripts.Script$1$\^eval\_.:program(<eval>:2)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        ... 29 more
Exception: Failed to execute script:

                        importClass(org.apache.pivot.wtk.Component);
                        importClass(org.apache.pivot.wtk.Keyboard);

                        function keyPressed(component, keyCode, keyLocation) {
                            if (keyCode == Keyboard.KeyCode.ENTER) {
                                rgdialog.close();
                            }
                        }

org.apache.pivot.serialization.SerializationException: Failed to execute script:

                        importClass(org.apache.pivot.wtk.Component);
                        importClass(org.apache.pivot.wtk.Keyboard);

                        function keyPressed(component, keyCode, keyLocation) {
                            if (keyCode == Keyboard.KeyCode.ENTER) {
                                rgdialog.close();
                            }
                        }

        at org.apache.pivot.beans.BXMLSerializer.reportException(BXMLSerializer.java:1438)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1293)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:447)
        at org.apache.pivot.beans.BXMLSerializer.processStartElement(BXMLSerializer.java:909)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:442)
        at org.apache.pivot.beans.BXMLSerializer.processStartElement(BXMLSerializer.java:909)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:442)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:633)
        at org.apache.pivot.beans.BXMLSerializer.readObject(BXMLSerializer.java:606)
        at com.dcp.sm.gui.pivot.Master.startup(Master.java:161)
        at org.apache.pivot.wtk.DesktopApplicationContext$2.run(DesktopApplicationContext.java:641)
        at org.apache.pivot.wtk.ApplicationContext$QueuedCallback.run(ApplicationContext.java:1656)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 2
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:467)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:451)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.apache.pivot.beans.BXMLSerializer.processEndElement(BXMLSerializer.java:1291)
        ... 24 more
Caused by: <eval>:2 ReferenceError: "importClass" is not defined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
        at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
        at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1426)
        at jdk.nashorn.internal.scripts.Script$2$\^eval\_.:program(<eval>:2)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
        ... 29 more
[DEBUG] Scan Mode set to SIMPLE_SCAN
[DEBUG] All Groups erased.
[DEBUG] All Packs erased.
[DEBUG] Export path set to file: C:\Users\user\DCP Setup Maker\target\Package-1.0.0.jar
[DEBUG] Build Mode set to IzPack
[DEBUG] Window open
```

**Comment by saidelimam** [comment]
This is due to a compatibility problem with Java JDK 8
Issue linked to #1

**Comment by fdrsuisse** [comment]
Hi I am using Java 8 and I get the error :
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ch.archimede.uads.common.ApplicationModule.executeAction(ApplicationModule.java:831)
	at ch.archimede.uads.common.Device.executeAction(Device.java:143)
	at jdk.nashorn.internal.scripts.Script$4$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
How can fix it ? Thanks in advance
